cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('<int:product_id>/add/', views.cart_add, name='add_cart'),
    path('<int:product_id>/remove/', views.cart_remove, name='cart_remove'),

]

contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'
urlpatterns = [
    path('delivery/', views.contactList, name='contactList'),
]

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('order_create/', views.order_create, name='order_create'),
    path('order_done/', views.done, name='order_done')
]

product/urls.py
from django.urls import path
from product import views

app_name = 'product'
urlpatterns = [
    path('main/', views.main, name='main'),
    path('menu/', views.menu, name='menu'),
    #path('<int:kind_id>/product/', views.productList, name='productList'),
]

prog_deep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('product.urls')),
    path('', include('promotions.urls')),
    path('', include('contacts.urls')),
    path('cart', include('cart.urls')),
    path('', include('order.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

promotions/urls.py
from django.urls import path
from promotions import views

app_name = 'promotions'
urlpatterns = [
    path('promotions/', views.promotionsList, name='promotionsList'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views
from users.views import RegisterFormView
app_name = 'users'
urlpatterns = [
    path('register/', RegisterFormView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from product.models import Product


class Order(models.Model):
    email = models.EmailField(verbose_name='Електронна пошта')
    first_name = models.CharField(max_length=50, verbose_name='Імя')
    last_name = models.CharField(max_length=50, verbose_name='Прізвище')
    number_tel = models.CharField(max_length=12, blank=True, verbose_name='Номер телефону')
    address = models.CharField(max_length=250, verbose_name='Адреса')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def get_count_goods(self):
        return Order.objects.count()

    def __str__(self):
        return self.first_name.join(' ').join(self.last_name)


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Замовив(ла)')
    product = models.CharField(max_length=200, verbose_name='Товар')
    price = models.FloatField(default=0, verbose_name='Ціна')
    created = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Дата створення')

    class Meta:
        verbose_name = 'Замовлений товар'
        verbose_name_plural = 'Замовлені товари'

promotions/models.py
from django.db import models


class Promotions(models.Model):
    name = models.CharField(max_length=100, verbose_name='Назва акції')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    description = models.CharField(max_length=500, blank=True, verbose_name='Опис')
    end = models.CharField(max_length=100, blank=True, verbose_name='Кінець акції')
    image = models.ImageField(upload_to='images', verbose_name='Обрати фото')

    class Meta:
        verbose_name = 'Акція'
        verbose_name_plural = 'Акції'

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, label='f', coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):
    email = forms.EmailField(help_text='Вкажіть вашу електронну пошту', label='Електронна пошта',
                             error_messages={'required': ''})
    first_name = forms.CharField(help_text='Вкажіть ваше імя', label='Імя', error_messages={'required': ''})
    last_name = forms.CharField(help_text='Вкажіть ваше прізвище', label='Прізвище', error_messages={'required': ''})
    number_tel = forms.CharField(help_text='Вкажіть ваш мобільний номер', label='Номер телефону', error_messages={'required': ''})
    address = forms.CharField(help_text='Вкажіть вашу адресу проживання, наприклад : "Мазепи 42"', label='Адреса',
                              error_messages={'required': ''})

    class Meta:
        model = Order
        fields = ['email', 'first_name', 'last_name', 'number_tel', 'address']

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartForm
from product.models import Product


@require_POST
def cart_add(request, product_id):
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart, 'total_price': cart.get_total_price()})

order/views.py
from django.shortcuts import render, redirect
from cart.cart import Cart
from order.forms import OrderForm
from order.models import OrderProduct


def order_create(request):
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        order = form.save()
        mass = []
        for item in cart:
            text_product = str(item['name']) + ' - ' + str(item['quantity'])
            mass.append(text_product)
        mass_str = '; '.join(mass)
        OrderProduct.objects.create(
            order=order,
            product=mass_str,
            price=cart.get_total_price(),
        )
        cart.clear()
        return redirect('order:order_done')
    else:
        form = OrderForm(request.POST)
    return render(request, 'order.html', {'form': form,
                                                'cart': cart,
                                                'get_total_price': cart.get_total_price()})


def done(request):
    if not request.user.is_authenticated:
        return redirect('users:login')
    return render(request, 'order_done.html')

promotions/views.py
from django.shortcuts import render, redirect
from promotions.models import Promotions


def promotionsList(request):
    if not request.user.is_authenticated:
        return redirect('users:login')
    return render(request, 'promotions.html', {'prom_list': Promotions.objects.all()})

templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block title %}<title>Havka</title>{% endblock %}
<style>
    div.menu a {
    color: white;
    display: block;
    text-align: center;

    text-decoration: none;
    width: 144.7px;
    height: 40px;
    float: left;
    margin: 3px 2px 2px 3px;
    font-size: 14pt;
    letter-spacing: 3px;
    font-family: arial;
    padding: 12px 0px 0px 0px;

    background: #DEB887;
    transition-property: background;
    transition-duration: 1s;
    transition-timing-function: linear;
}   </style>

</head>
<body>
<div id="mainpage">
<header>

{% block background %}
    <h1>Image</h1>
{% endblock %}

<div class="menu" id="a">
    <a href="{% url 'product:main' %}">Головна</a>
    <a href="{% url 'product:menu' %}">Меню</a>
    <a href="{% url 'contacts:contactList' %}">Доставка</a>
    <a href="{% url 'promotions:promotionsList' %}">Акції</a>
    <a href="{% url 'users:login' %}">Вхід</a>
    <a href="{% url 'cart:cart_detail' %}">Корзина</a>
</div>
</header>

{% block content %}

    <h1>Content</h1>

{% endblock %}

<footer>
<p> </p>
<br>
      <h3><p> Наші контакти:</p></h3>
    <div>
            <ul>
                {% for contact in contacts %}
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-pin-map-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M3.1 11.2a.5.5 0 0 1 .4-.2H6a.5.5 0 0 1 0 1H3.75L1.5 15h13l-2.25-3H10a.5.5 0 0 1 0-1h2.5a.5.5 0 0 1 .4.2l3 4a.5.5 0 0 1-.4.8H.5a.5.5 0 0 1-.4-.8l3-4z"/>
                            <path fill-rule="evenodd"
                                  d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999z"/>
                        </svg>    {{ contact.address }}</li>
                    <br>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-telephone" viewBox="0 0 16 16">
                            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>

                        </svg>    {{ contact.number_tel }}</li>
                    <br>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-envelope" viewBox="0 0 16 16">
                            <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
                        </svg>    {{ contact.email }}</li>
                    <br>

                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                            <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
                        </svg>    {{ contact.schedule }}</li>
                {% endfor %}
            </ul>
        <br>
        </div>
</footer>

</div>
</body>
</html>

templates/cart.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Корзина</title>
{% endblock %}
{% block background %}
    <div class="banner" id="p"><img src="{% static 'img/5.jpg' %}"></div>
{% endblock %}
{% block content %}
    <h1>Ваша корзина</h1>
    <ul>
        {% for item in cart %}
            <li>Назва: {{ item.name }}</li>
            <li>Кількість: {{ item.quantity }}</li>
            <li>Ціна: {{ item.price }}</li>
            <a href="{% url "cart:cart_remove" item.id %}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
                    <path fill-rule="evenodd"
                          d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
                </svg>
            </a>
        {% endfor %}
        <h2>Загальна ціна: {{ total_price }} гривень</h2>
    </ul>
    <p class="text-right">
        <a href="{% url "product:menu" %}" class="glow-button">Продовжити покупки</a>
        <a href="{% url "order:order_create" %}" class="glow-button">Підтвердити замовлення</a>
    </p>
{% endblock %}

templates/delivery.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Доставка</title>
{% endblock %}

{% block background %}
    <div class="banner" id="p"><img src="{% static 'img/3.jpg' %}" alt="Image"></div>
{% endblock %}

{% block content %}
    <div class="cont" id="img">
        <h1> Доставка і оплата </h1>
        <h4><p><font color="#FFDEAD"> Доставка їжі не обмежена територіально! </font></p></h4>
        <ul>
            <li><p> Безкоштовна доставка їжі по Івано-Франківську без мінімальної суми замовлення.</p></li>
            <li><p> Час доставки від 60 до 90 хвилин.</p></li>
        </ul>
        <h2><p><font color="#CD853F"> Здійснення оплати </font></p></h2>
        <p>Для зручного замовлення страв ми подбали про різні способи оплати замовлень, які не тільки прості, але і
            допоможуть Вам заощадити Ваш час. </p>
        <p>Оплата може бути здійснена двома способами:</p>
        <ol>
            <li><p>Оплата кур'єру готівкою при отриманні замовлення;</p></li>
            <li><p>Оплата кур'єру за допомою банківської карти при отриманні замовлення;</p></li>
        </ol>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title> Головна </title>
{% endblock %}

{% block background %}
<div class="banner" id="p"><img src="{% static 'img/1.jpg' %}" alt="Image"></div>
{% endblock %}

{% block content %}
<div class="content">
<p>

<h1> <em>  <font color="#FFEFD5">Доставка їжі в Івано-Франкіську цілодобово - Havka.if.ua </font></em> </h1> 

</p>


<p>Власне, що може бути легше, ніж зробити замовлення повертаючись додому після насиченого робочого дня або ж насолодитися смачненьким обідом одразу на робочому місці. Запас продуктів вичерпався, а шлунок вимагає власну порцію або ж до Вас несподівано приїхали гості? Доставка їжі в Івано-Франквську прийде на допомогу. Замовити можливо все - суші, піца, закуски, супи, гарніри та напої на любий смак! </p>


<p><font color="#FFDEAD">Доставка їжі здійснюється цілодобово в будь-який район міста!</font></p>

<p><font color="#E9967A">Ми гарантуємо Вам індивідуальний підхід та якісне обслуговування з кардинально новою концепцією, в яку входять:</font></p>
<ul>
  <li> <p> <font color="#E9967A">приготування смачних і корисних страв з цікавою подачею від наших шеф-кухарів;</font></p> </li> 
  <li> <p> <font color="#E9967A">використання тільки свіжих інгредієнтів, що постачаються в ресторан напряму від виробника;</font></p></li>
   <li> <p> <font color="#E9967A">відмова від барвників, консервантів та шкідливих хімічних добавок - ми використовуємо тільки натуральні складові страв;</font> </p></li>
  <li> <p> <font color="#E9967A">оперативна доставка обідів в будь-який район міста;</font> </p></li>
   <li> <p> <font color="#E9967A">приємні ціни на все меню;</font> </p></li>
   <li><p> <font color="#E9967A">уважний та ввічливий підхід до бажань кожного клієнта.</font></p></li>
</ul>
<p>Наша доставка смачної їжі цілодобово підходить на всі випадки життя - легкий перекус чи ситний обід, вечірні посиденьки з друзями або романтичну вечерю. </p>
</div>
{% endblock %}
</body>
</html>

templates/menu.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Меню</title>
{% endblock %}

{% block background %}
    <div class="banner" id="p"><img src="{% static 'img/5.jpg' %}"></div>
{% endblock %}

{% block content %}
    <div class="content">
        {% for product in product_list %}
            <h1> {{ product.name }} </h1>
            <p>{{ product.description }}</p>
            {% with product.RelProduct.all as product_item %}
                {% for item in product_item %}
                    <p>
                    <table>
                        <tr>
                            <td rowspan="6"><img src="{{ item.image.url }}" alt="" class="scale"></td>
                            <th colspan="3"><font color="#FFDEAD"> {{ item.name }}</th>
                        </tr>
                        <tr>
                            <td colspan="3"><font color="#FFDEAD"> Вага: {{ item.mass }} грам</td>
                        </tr>
                        <tr>
                            <td colspan="3"><font color="#FFDEAD"> {{ item.price }} грн</td>
                        </tr>
                        <tr>
                            <td colspan="3"><font color="#FFDEAD"> {{ item.description }}</td>
                        </tr>
                        <tr>
                            <td>
                                <form action="{% url "cart:add_cart" item.id %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_form.quantity }}
                            </td>
                            <td><input type="submit" class="glow-button" value="В КОШИК"></td>
                        </tr>
                        </form>

                    </table></p>


                {% endfor %}
            {% endwith %}
        {% endfor %}
    </div>
{% endblock %}

templates/order.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>Замовлення</title>
{% endblock %}
{% block background %}
    <div class="banner" id="p"><img src="{% static 'img/5.jpg' %}"></div>
{% endblock %}
{% block content %}
    <ul>
        {% for item in cart %}
            <li><h4>Назва товару: {{ item.name }}</h4></li>
            <li><h4>Кількість: {{ item.quantity }}</h4></li>
        {% endfor %}
        <li><h4>Загальна вартість покупки: </h4><h3>{{ get_total_price }} гривень</h3></li>
    </ul>
    <form action="." method="POST">
    {% csrf_token %}
        <table>{{ form }}</table>
    <br>
    <input type="submit" value="Створити замовлення">
    </form>
{% endblock %}

templates/order_done.html
{% extends 'base.html' %}
{% load static %}
{% block background %}
    <div class="banner" id="p"><img src="{% static 'img/5.jpg' %}"></div>
{% endblock %}
{% block content %}
    <h1>Замовлення створено!</h1>
    <br>

{% endblock %}

templates/promotions.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	<title>Акції</title>
{% endblock %}

{% block background %}
<div class="banner" id="p"><img src="{% static 'img/4.jpg' %}"></div>
{% endblock %}

{% block content %}
<div class="content" id="img">
	<h1>Знижки та акції</h1>
	<h3><p> Пропонуємо Вам скористатися акціями нашої доставки, які ми розробили спеціально для наших шановних клієнтів.</h3></p>
	<p><table>
    {% for prom in prom_list %}
		<tr><td rowspan="4"><img src="{{ prom.image.url}}" alt="" class="scale"></td>
            <th> <font color="#FFDEAD" size="5">Акція: {{ prom.name }}</font></th></tr>
        <tr><td><font color="#FFDEAD" size="4"> {{ prom.title }}</font></td></tr>
			<tr><td><form>
<input type="button" class="floating-button" value="Детальніше" onClick="alert('{{ prom.description }}')">
</form> </td></tr>
        <tr><td><font color="#FFDEAD"> {{ prom.end }}</font></td></tr>
    {% endfor %}
</table></p>

</div>

{% endblock %}